//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LigalFrontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gen_recogidas
    {
        public int ID { get; set; }
        public Nullable<int> IDRUTA { get; set; }
        public Nullable<int> IDPUNTO { get; set; }
        public Nullable<int> IDUSUARIO { get; set; }
        public Nullable<int> IDCLIENTE { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string HORA { get; set; }
        public Nullable<int> GRADDEJA { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<int> GRADRECOGE { get; set; }
        public Nullable<int> NUMFRASCOS { get; set; }
        public string ROWID { get; set; }
        public Nullable<int> IDSERIE { get; set; }
        public Nullable<int> IDMONEDA { get; set; }
        public string NOMCLIENTE { get; set; }
        public string DIRCLIENTE { get; set; }
        public Nullable<int> IDTIPODOC { get; set; }
        public Nullable<int> NUMERO { get; set; }
        public string NUMCOMPLETO { get; set; }
        public Nullable<int> IDEMPRESA { get; set; }
        public Nullable<int> GRESTIMADAS { get; set; }
        public Nullable<int> IDMOTIVO { get; set; }
        public Nullable<System.DateTime> FPROGRAMADA { get; set; }
        public Nullable<int> EXECUTED { get; set; }
        public Nullable<int> PROGRAMADA { get; set; }
        public Nullable<int> IDLIGAL { get; set; }
        public Nullable<int> MAIL { get; set; }
    }
}
