//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LigalFrontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gen_usuarios
    {
        public int ID { get; set; }
        public Nullable<int> IDEMPRESA { get; set; }
        public Nullable<int> IDTIPO { get; set; }
        public string LOGIN { get; set; }
        public string PWD { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO1 { get; set; }
        public string APELLIDO2 { get; set; }
        public Nullable<int> DERECHOS { get; set; }
        public string ROWID { get; set; }
        public Nullable<int> CODIGO { get; set; }
        public string USERTYPE { get; set; }
    }
}
