//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LigalFrontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gen_inspecciones
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> FechaHoraRegistro { get; set; }
        public Nullable<System.DateTime> FechaHoraVisita { get; set; }
        public string TipoInspeccion { get; set; }
        public string Situacion { get; set; }
        public Nullable<int> IDUsuario { get; set; }
        public string IDMuestraRecogida { get; set; }
        public string IDExplotacion { get; set; }
        public string IDMuestraOrigen { get; set; }
        public Nullable<System.DateTime> FechaMuestraOrigen { get; set; }
        public Nullable<System.DateTime> FechaAnalisisOrigen { get; set; }
        public string ResultadoCHARM { get; set; }
        public string IDIndustria { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> Informado { get; set; }
        public string ROWID { get; set; }
        public Nullable<int> Actualizado { get; set; }
        public string Resultado { get; set; }
        public Nullable<System.DateTime> FechaSiguienteVisita { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Poblacion { get; set; }
        public string Provincia { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string INDUSTRIAN { get; set; }
        public Nullable<int> IDORIGEN { get; set; }
        public Nullable<int> Destrucion { get; set; }
        public Nullable<int> NumeroVisita { get; set; }
        public Nullable<int> LitrosLeche { get; set; }
        public Nullable<int> NumMuxiduras { get; set; }
        public Nullable<int> SERIEGANADERO { get; set; }
        public Nullable<int> IDOBSERVA { get; set; }
        public Nullable<int> MAMITE { get; set; }
        public Nullable<int> MAMITESN { get; set; }
        public Nullable<int> OUTRAS { get; set; }
        public Nullable<int> OUTRASSN { get; set; }
        public Nullable<int> PARTO { get; set; }
        public Nullable<int> PARTOSN { get; set; }
        public Nullable<int> ASOCIACION { get; set; }
        public Nullable<int> ASOCIACIONSN { get; set; }
        public Nullable<int> EMPDOSIS { get; set; }
        public Nullable<int> TRATAINTRAM { get; set; }
        public Nullable<int> ORDEMUXI { get; set; }
        public Nullable<int> MUXIERRO { get; set; }
        public Nullable<int> INCORPORACION { get; set; }
        public Nullable<int> NOIDENTIF { get; set; }
        public Nullable<int> TRATANIERR { get; set; }
        public Nullable<int> ERRCOMUNI { get; set; }
        public Nullable<int> NONCAUSA { get; set; }
        public Nullable<int> ALGUNTRATA { get; set; }
        public Nullable<int> NONCOMPROBAT { get; set; }
        public Nullable<int> NONADMINT { get; set; }
        public Nullable<int> NONPPOSIBLEE { get; set; }
        public string OBSTRATA { get; set; }
        public Nullable<int> VacasLacta { get; set; }
        public Nullable<int> NONDESTRUCION { get; set; }
        public Nullable<int> MODIFICADO { get; set; }
        public string COORDX { get; set; }
        public string COORDY { get; set; }
        public Nullable<double> POSX { get; set; }
        public Nullable<double> POSY { get; set; }
        public Nullable<int> INCORPORACACION { get; set; }
        public Nullable<int> NONPOSIBLEE { get; set; }
        public string DIRGPS { get; set; }
        public string RESULTADOQUINO { get; set; }
        public Nullable<int> SOLICITATEST { get; set; }
        public Nullable<int> XONE { get; set; }
        public string FOTO1 { get; set; }
        public string FOTO2 { get; set; }
        public string FOTO3 { get; set; }
        public string VIDEO { get; set; }
    }
}
