//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LigalFrontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gen_monedas
    {
        public int ID { get; set; }
        public string ETIQUETA { get; set; }
        public string SIMBOLO { get; set; }
        public Nullable<double> CAMBIO { get; set; }
        public Nullable<int> NDIGITOS { get; set; }
        public Nullable<System.DateTime> FBAJA { get; set; }
        public Nullable<int> BAJA { get; set; }
        public string ROWID { get; set; }
    }
}
