//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LigalFrontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEN_PUNTOSRECOGIDA
    {
        public int ID { get; set; }
        public string CODIGOP { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<double> COORDX { get; set; }
        public Nullable<double> COORDY { get; set; }
        public Nullable<double> POSX { get; set; }
        public Nullable<double> POSY { get; set; }
        public string ROWID { get; set; }
        public string DIRGPS { get; set; }
        public Nullable<int> IDUSUARIO { get; set; }
        public Nullable<int> IDUSUARIOR { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<double> DISTANCIA { get; set; }
    }
}
