//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LigalFrontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gen_puntosenruta
    {
        public int ID { get; set; }
        public Nullable<int> IDPUNTO { get; set; }
        public Nullable<int> IDRUTA { get; set; }
        public Nullable<int> NUMGRADILLAS { get; set; }
        public string ROWID { get; set; }
    }
}
