//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LigalFrontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gen_series
    {
        public int ID { get; set; }
        public string SERIE { get; set; }
        public string DESCRIPCION { get; set; }
        public string PREFIJO { get; set; }
        public string SUFIJO { get; set; }
        public string SIGNO { get; set; }
        public Nullable<int> IDEMPRESA { get; set; }
        public Nullable<int> PRIMERO { get; set; }
        public string ROWID { get; set; }
    }
}
