//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LigalFrontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gen_trata
    {
        public int ID { get; set; }
        public Nullable<int> IDINSP { get; set; }
        public Nullable<System.DateTime> FECHAT { get; set; }
        public Nullable<int> IDTRATA { get; set; }
        public string ROWID { get; set; }
    }
}
