//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LigalFrontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gen_clientes
    {
        public int ID { get; set; }
        public string CODIGOC { get; set; }
        public string NOMBREC { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        public string MOVIL { get; set; }
        public string EMAIL { get; set; }
        public string ROWID { get; set; }
        public string POBLACION { get; set; }
        public string PROVINCIA { get; set; }
        public string CPOSTAL { get; set; }
    }
}
