//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LigalFrontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gen_tiposDocumento
    {
        public int ID { get; set; }
        public string SIMBOLO { get; set; }
        public string DESCRIPCION { get; set; }
        public string REPORTE { get; set; }
        public string OPCIONES { get; set; }
        public string PLANTILLA { get; set; }
        public string LINEAS { get; set; }
        public Nullable<int> ENCABEZADO { get; set; }
        public string ROWID { get; set; }
    }
}
