//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LigalFrontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gen_Correos
    {
        public int ID { get; set; }
        public string DIRFROM { get; set; }
        public string DIRTO { get; set; }
        public string CC { get; set; }
        public string ASUNTO { get; set; }
        public string CUERPO { get; set; }
        public Nullable<int> ENVIADO { get; set; }
        public string ROWID { get; set; }
        public string SERVER { get; set; }
        public string ATTACHMENT { get; set; }
    }
}
