//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LigalFrontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gen_conectargps
    {
        public int ID { get; set; }
        public string LONGITUD { get; set; }
        public string LATITUD { get; set; }
        public string RUMBO { get; set; }
        public string FGPS { get; set; }
        public string HGPS { get; set; }
        public string STATUS { get; set; }
        public string ROWID { get; set; }
    }
}
