//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LigalFrontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEN_CONTROLTEMPERATURA
    {
        public int ID { get; set; }
        public Nullable<int> IDUSUARIO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string CODPUNTO { get; set; }
        public string COORDX { get; set; }
        public string COORDY { get; set; }
        public Nullable<double> POSX { get; set; }
        public Nullable<double> POSY { get; set; }
        public string OBSERVA { get; set; }
        public string ROWID { get; set; }
    }
}
