//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LigalFrontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gen_bolsas
    {
        public int ID { get; set; }
        public string CODIGOB { get; set; }
        public Nullable<int> IDCLIENTE { get; set; }
        public Nullable<int> IDMOTIVO { get; set; }
        public Nullable<System.DateTime> FECHASALIDA { get; set; }
        public string FECHAENTREGA { get; set; }
        public string TIPOINFO { get; set; }
        public string OBSERVACIONES { get; set; }
        public string ROWID { get; set; }
        public Nullable<int> IDSERIE { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<int> IDMONEDA { get; set; }
        public string NOMCLIENTE { get; set; }
        public string DIRCLIENTE { get; set; }
        public Nullable<int> IDTIPODOC { get; set; }
        public Nullable<int> NUMERO { get; set; }
        public string NUMCOMPLETO { get; set; }
        public Nullable<int> IDEMPRESA { get; set; }
        public string ROWGUID { get; set; }
        public Nullable<int> IDPUNTO { get; set; }
        public Nullable<int> EXECUTED { get; set; }
    }
}
