//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LigalFrontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gen_empresa
    {
        public int ID { get; set; }
        public Nullable<int> IDPADRE { get; set; }
        public Nullable<int> IDMONEDA { get; set; }
        public Nullable<int> CODIGO { get; set; }
        public string ETIQUETA { get; set; }
        public string NOMBRE2 { get; set; }
        public string NIF { get; set; }
        public string TIPOVIA { get; set; }
        public string CALLE { get; set; }
        public string NUMERO { get; set; }
        public string ESCALERA { get; set; }
        public string PISO { get; set; }
        public string PUERTA { get; set; }
        public string POBLACION { get; set; }
        public string CP { get; set; }
        public string PROVINCIA { get; set; }
        public string TELEFONO { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public string URL { get; set; }
        public string CUENTACONT { get; set; }
        public string CUENTABANC { get; set; }
        public Nullable<int> RECARGO { get; set; }
        public Nullable<int> OPCIONES { get; set; }
        public string ROWID { get; set; }
    }
}
