//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LigalFrontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gen_actionlogs
    {
        public int ID { get; set; }
        public Nullable<int> IDSEARCH { get; set; }
        public string VE_NUM_IDENTIF { get; set; }
        public string VE_NUM_ALIAS { get; set; }
        public string VE_PAIS { get; set; }
        public Nullable<int> VE_NUM_ALIAS_2 { get; set; }
        public string VE_TIPO_REGISTRO { get; set; }
        public Nullable<int> NEWACTION { get; set; }
        public string NOMTABLA { get; set; }
        public Nullable<int> TIPO { get; set; }
        public string VI_NUM_IDENTIF_V { get; set; }
        public string VI_NUM_IDENTIF_I { get; set; }
        public string DO_NUM_IDENTIF_V { get; set; }
        public string DO_NUM_IDENTIF_I { get; set; }
        public string DO_CLAVE_DOMICILIO { get; set; }
        public Nullable<int> MID { get; set; }
        public string PB_NUM_NAC_IDEN { get; set; }
        public string PB_PAIS { get; set; }
        public string PB_NUM_IDENTIF { get; set; }
        public Nullable<int> PB_NUM_ALIAS { get; set; }
        public string PB_TIPO_REGISTRO { get; set; }
        public string NTRANSFORM { get; set; }
        public string NTRANSFORMSEARCH { get; set; }
        public string ROWID { get; set; }
    }
}
