//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LigalFrontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gen_recogidasR
    {
        public int ID { get; set; }
        public Nullable<int> IDCLIENTE { get; set; }
        public Nullable<int> GRESTIMADAS { get; set; }
        public Nullable<int> GRADDEJA { get; set; }
        public Nullable<int> GRADRECOGE { get; set; }
        public Nullable<int> NUMFRASCOS { get; set; }
        public string ROWID { get; set; }
        public Nullable<int> IDRECOGIDA { get; set; }
        public Nullable<int> IDOBSERVA { get; set; }
        public string OBSERVACIONES { get; set; }
        public string FOTO1 { get; set; }
        public string FOTO2 { get; set; }
        public string FOTO3 { get; set; }
        public string VIDEO { get; set; }
    }
}
