//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LigalFrontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEN_COORDENADASGPS
    {
        public int ID { get; set; }
        public Nullable<int> IDEMPRESA { get; set; }
        public Nullable<int> IDUSUARIO { get; set; }
        public Nullable<double> LATITUDGPS { get; set; }
        public Nullable<double> LONGITUDGPS { get; set; }
        public Nullable<double> RUMBOGPS { get; set; }
        public Nullable<System.DateTime> FECHAHORAGPS { get; set; }
        public Nullable<System.DateTime> FECHAHORAPDA { get; set; }
        public Nullable<int> OPCIONES { get; set; }
        public Nullable<int> OP1 { get; set; }
        public string ROWID { get; set; }
        public string NPUNTO { get; set; }
        public Nullable<double> DISTANCIA { get; set; }
    }
}
