//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LigalFrontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gen_programacion
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string RECOGEDOR { get; set; }
        public string CODPUNTO { get; set; }
        public string INDUSTRIA { get; set; }
        public Nullable<int> NUM_MUESTRAS { get; set; }
        public Nullable<int> OK { get; set; }
        public Nullable<int> IDX { get; set; }
        public string ROWID { get; set; }
    }
}
