//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LigalFrontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gen_visitas
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DATAFICHA { get; set; }
        public string GANDEIRO { get; set; }
        public Nullable<int> SERIE { get; set; }
        public Nullable<System.DateTime> DATAMOSTRA { get; set; }
        public string RESULTADO { get; set; }
        public Nullable<int> NUMVACAS { get; set; }
        public Nullable<int> LITROSLEITE { get; set; }
        public string RESULTADOCHARM { get; set; }
        public Nullable<bool> MAMITES { get; set; }
        public Nullable<bool> PRESCRIPCION { get; set; }
        public Nullable<bool> REXTRATAMENTO { get; set; }
        public Nullable<bool> RECEITAS { get; set; }
        public Nullable<bool> ALMACENAMED { get; set; }
        public Nullable<bool> TEMPESPMAL { get; set; }
        public Nullable<bool> TEMPESPINCUMP { get; set; }
        public Nullable<bool> TEMPESPAXUST { get; set; }
        public Nullable<bool> TARTASECFORA { get; set; }
        public Nullable<bool> OUTROSMEDIC { get; set; }
        public Nullable<bool> TRATAINTRAMAMA { get; set; }
        public Nullable<bool> ORDMUXINCORREC { get; set; }
        public Nullable<bool> UTILMEDINADEC { get; set; }
        public Nullable<bool> ANIMALNOVO { get; set; }
        public Nullable<bool> OUTROS { get; set; }
        public string OBSERVA { get; set; }
        public Nullable<int> ACTUALIZADO { get; set; }
        public string ROWID { get; set; }
    }
}
