//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LigalFrontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gen_inicioruta
    {
        public int ID { get; set; }
        public string INICIORUTA { get; set; }
        public Nullable<int> IDRUTA { get; set; }
        public string HORARUTA { get; set; }
        public Nullable<double> KMINICIO { get; set; }
        public Nullable<double> KMFIN { get; set; }
        public Nullable<double> TOTALKM { get; set; }
        public string ROWID { get; set; }
        public Nullable<int> IDUSUARIO { get; set; }
        public Nullable<int> ABIERTA { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    }
}
