//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LigalFrontend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class master_replica_queue
    {
        public int ID { get; set; }
        public string ROWID { get; set; }
        public string OPERID { get; set; }
        public string TIMESTAMP { get; set; }
        public Nullable<int> OPER { get; set; }
        public Nullable<int> MID { get; set; }
        public string SQL { get; set; }
        public Nullable<int> DMID { get; set; }
        public Nullable<int> CONDITIONAL { get; set; }
        public string TBL { get; set; }
        public Nullable<int> DMIDPR { get; set; }
        public Nullable<int> DISABLED { get; set; }
        public Nullable<int> BATCHSIZE { get; set; }
        public Nullable<System.DateTime> RCVTIMESTAMP { get; set; }
        public Nullable<System.DateTime> PRTIMESTAMP { get; set; }
    }
}
